stages:
- mavenbuild
- maventest
- autodeploy
- androidbuild
- androidtest
#
maven-build:
  stage: mavenbuild
  tags:
  - backend
  script:
  - cd Backend/SD2Server
  - mvn package -B
#
maven-test:
  stage: maventest
  tags:
  - backend
  script:
  - cd Backend/SD2Server
  - mvn test
  artifacts:
   paths:
   - Backend/SD2Server/target/*.jar
#
autoDeploy:
  stage: autodeploy
  tags:
  - backend
  script:
  - cd Backend/SD2Server
  - mvn package
  - sudo mv target/*.jar /target/web-demo.jar
  - sudo systemctl stop system-web-demo
  - sudo systemctl start system-web-demo
#
android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/gradlew
  tags:
  - android 
  script:
  - cd Frontend
  - ./gradlew assemble
  artifacts:
   paths:
    - cd Frontend/app/build/outputs/
#
unitTest:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./Frontend/gradlew
  tags:
  - android
  script:
  - cd Frontend
  - ./gradlew test
